PokemongoBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: PokemongoBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        date:
            type: datetime
        comment:
            type: string
            length: 255
    lifecycleCallbacks: {  }
