pokemongo_feature:
    resource: "@PokemongoBundle/Resources/config/routing/feature.yml"
    prefix:   /feature

pokemon_index:
    path:     /
    defaults: { _controller: "PokemongoBundle:feature:index" }
    methods:  GET

pokemon_show:
    path:     /{id}
    defaults: { _controller: "PokemongoBundle:feature:show" }
    methods:  GET

pokemon_new:
    path:     /new
    defaults: { _controller: PokemongoBundle:feature:new }
    methods:  [GET, POST]

pokemon_edit:
    path:     /{id}/edit
    defaults: { _controller: "PokemongoBundle:feature:edit" }
    methods:  [GET, POST]

pokemon_delete:
    path:     /{id}/delete
    defaults: { _controller: "PokemongoBundle:feature:delete" }
    methods:  DELETE

post_com:
    path:     /comment/{id}
    defaults: { _controller: PokemongoBundle:feature:newCom }