<?php

namespace PokemongoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * featureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class featureRepository extends EntityRepository
{
}
